#!/bin/bash
# Script : easynginx
# Version: 3.0
# Coder  : Ahmed Kandil .. continual with Ahmed Tohamy, Mahmoud Ahmed
# Last Update : 16-07-2012


# Set of Variables :

URL=http://monitor.arabhosters.com/sources/nginx
# The link for Nginx init script
nginxst="$URL/nginxinit"
# The link for PHP-FPM init script
phpfpm="$URL/php-fpminit"
# The link for PHP-FPM conf file
phpfpm_conf="$URL/php-fpm.conf"
# The link for php.ini file
phpini="$URL/php.ini"
# The link for mod_rpaf
S_RPAF="$URL/mod_rpaf-0.6.tar.gz"
NGINX_PATH=/usr/local/nginx
FPM_PATH=/usr/local/php-fpm/etc
Apache_Port=82
BASE=/usr/local/src/EasyNginx

# Template Files
CONF_TEMPLATE_URL="$URL/ntemplate.tar.gz"


# Start Colors
DarkGrey="$(tput bold ; tput setaf 0)"
LightGrey="$(tput setaf 7)"
White="$(tput bold ; tput setaf 7)"
Red="$(tput setaf 1)"
LightRed="$(tput bold ; tput setaf 1)"
Green="$(tput setaf 2)"
LightGreen="$(tput bold ; tput setaf 2)"
Yellow="$(tput bold ; tput setaf 3)"
Blue="$(tput setaf 4)"
LightBlue="$(tput bold ; tput setaf 4)"
NC="$(tput sgr0)" # No Color
# End Color

InsertSection()
{
	echo ""
	echo "[+] ${Yellow}$1${NC}"
	echo "------------------------------------"
}

do_repo()
{
InsertSection "-- Checking and Installing the required repos --"
# Check for the release and version :
rel=`cat /etc/redhat-release | cut -d" " -f3 | cut -d"." -f1`
ver=`uname -a | cut -d" " -f12`
     if [ -e /etc/yum.repos.d/epel.repo ] && [ -e /etc/yum.repos.d/centalt.repo ]
        then 
	  echo -e " - You Have the required repos\t\t\t         [ ${Green}Done${NC} ] "
	else (  	
	  if [ $rel == "5" ]
	    then (
    	    if [ $ver == "x86_64" ]
                   then (
		   rpm -Uvh http://mirror.de.leaseweb.net/epel/5/x86_64/epel-release-5-4.noarch.rpm
                   rpm -Uvh http://centos.alt.ru/repository/centos/5/x86_64/centalt-release-5-3.noarch.rpm
 			)
 
	    else
	    rpm -Uvh http://download.fedoraproject.org/pub/epel/5/i386/epel-release-5-4.noarch.rpm	
  	    rpm -Uvh http://centos.alt.ru/repository/centos/5/i386/centalt-release-5-3.noarch.rpm
	    fi
		 )
	  elif [ $rel == "6" ]
	        then (

		if [ $ver == "x86_64" ]
 			then (
		        rpm -Uvh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-5.noarch.rpm
			rpm -Uvh http://centos.alt.ru/repository/centos/6/x86_64/centalt-release-6-1.noarch.rpm  
 			     )
	        else
		rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-7.noarch.rpm
		rpm -Uvh http://centos.alt.ru/repository/centos/6/i386/centalt-release-6-1.noarch.rpm  
	        fi
		     )
	else
	  InsertSection "this script only for RedHat and CentOS "
	fi 
             )
	fi

}
# This function for installing Nginx :
do_Nginx()
{
 do_repo
 InsertSection " -- Installing Nginx -- "
 yum install pcre-devel.x86_64 openssl.x86_64 openssl-devel.x86_64 -y #> | tee -a $LOGFILE 
 #yum install google-perftools* -y
 yum install gcc* -y
 yum install pcre-devel* -y
 yum install bc -y

 cd /usr/local/
 wget http://nginx.org/download/nginx-1.2.0.tar.gz
 tar zxvf nginx-1.2.0.tar.gz
 cd nginx-1.2.0
 ./configure --prefix=/usr/local/nginx --with-http_stub_status_module --with-http_gzip_static_module --with-http_realip_module 
 make
 make install 
 wget $nginxst -O /etc/init.d/nginx
 chmod +x /etc/init.d/nginx
 
  chkconfig --add nginx
  chkconfig --level 345 nginx on

echo -e " -- Nginx Installed\t\t\t [ ${Green}Done${NC} ] "

}

# This function for installing PHP-FPM :
do_phpfpm()
{
   InsertSection " -- Installing PHP -- "

   yum install libxml2-devel bzip2-devel libjpeg-devel libX11-devel gd-devel libmcrypt-devel mysql-devel mhash-devel libevent-devel libtool-ltdl-devel curl-devel.x86_64 libc-client-devel.i386 libc-client-devel.i386 zlib-devel libpng-devel libxslt-devel -y
   yum install gcc* -y
   yum install bzip2-devel.x86_64 -y
   cd /usr/local/src
   wget http://autosetup1.googlecode.com/files/php-5.3.10.tar.gz
   tar -xzvf php-5.3.10.tar.gz && cd php-5.3.10
  ./configure --prefix=/usr/local/php-fpm --with-mysql --with-gd --with-gettext --with-libdir=lib64 --with-iconv  --enable-fpm --enable-mbstring --with-mysqli --with-openssl --with-pcre-dir --with-pcre-regex --enable-sockets --enable-wddx --with-pdo-mysql --enable-exif --enable-zip --enable-sysvshm --with-bz2 --with-pic --with-xmlrpc --enable-bcmath --enable-calendar --with-jpeg-dir --with-zlib
  
   make all
   make install
   wget $phpfpm_conf -O  /usr/local/php-fpm/etc/php-fpm.conf
   #cp /usr/local/php-fpm/etc/{php-fpm.conf.default,php-fpm.conf}
   #sed -i 's/;pid/pid/gi' /usr/local/php-fpm/etc/php-fpm.conf
   #sed -i 's/;error_log/error_log/gi' /usr/local/php-fpm/etc/php-fpm.conf  
   echo "include=/usr/local/php-fpm/etc/conf.d/*.conf" >> /usr/local/php-fpm/etc/php-fpm.conf
   if [ ! -e /usr/local/cpanel ] && [ ! -d $FPM_PATH/conf.d/  ]
    then
	mkdir $FPM_PATH/conf.d
	cp $BASE/nginx_template/default-fpm-site.tpl $FPM_PATH/conf.d/default-site.conf
   fi 
   wget $phpini -O /usr/local/php-fpm/lib/php.ini
   wget $phpfpm -O /etc/init.d/php-fpm 
   chmod +x /etc/init.d/php-fpm
   chkconfig --add php-fpm
   chkconfig --levels 235 php-fpm on
   rm -rf /usr/local/src/php-5.3.10
   echo -e " -- PHP Installed\t\t\t [ ${Green}Done${NC} ] "
}

# This function for Copying Nginx Configuration file and for check the services
do_phpfpmHandelNginx()
{

    mv  $NGINX_PATH/conf/nginx.conf  $NGINX_PATH/conf/nginx.conf.default
    cp -f $BASE/nginx_template/main.template $NGINX_PATH/conf/nginx.conf
     
    
    IP=`hostname -i`
    CPU=`cat /proc/cpuinfo |grep -c '^processor'`
    replace REP_IP $IP -- $NGINX_PATH/conf/nginx.conf > /dev/null 2>&1
    replace REP_CORES $CPU -- $NGINX_PATH/conf/nginx.conf > /dev/null 2>&1
    echo -e " - Check for Nginx Configuration file\t\t\t [ ${Green}Done${NC} ]"
InsertSection "Starting the required Service"
    if [ "$fpm" == "1" ]
		then
    			chkconfig --levels 235 httpd off
   			 /etc/init.d/httpd stop 2>&1
		         /etc/init.d/php-fpm start
			 /etc/init.d/php-fpm restart
			 /etc/init.d/nginx start
			 /etc/init.d/nginx restart
	
    elif [ "$fpm" == "0" ]
		then
                     if [ -e /usr/local/cpanel ]
 		     then
			chkconfig --levels 235 httpd on
		 	replace ":80" ":$Apache_Port" -- /usr/local/apache/conf/httpd.conf > /dev/null 2>&1
     	         	replace "apache_port=0.0.0.0:80" "apache_port=0.0.0.0:$Apache_Port" -- /var/cpanel/cpanel.config > /dev/null 2>&1
    		 	echo -e " - Updated Apache Port on Tweak Setting\t\t\t [ ${Green}Done${NC} ]"
       		 	/scripts/rebuildhttpdconf > /dev/null 2>&1
               	 	sleep 1
		 	echo -e " - Apache Config Rebuild\t\t\t         [ ${Green}Done${NC} ]"
    	 		/etc/init.d/php-fpm stop > /dev/null 2>&1
			/etc/init.d/httpd restart
			/etc/init.d/httpd restart
			/etc/init.d/nginx start
		 	/etc/init.d/nginx restart
                     else
                        replace "80" "$Apache_Port" -- /etc/httpd/conf/httpd.conf > /dev/null 2>&1
			/etc/init.d/php-fpm stop > /dev/null 2>&1
			/etc/init.d/httpd restart
			/etc/init.d/httpd restart
			/etc/init.d/nginx start
		        /etc/init.d/nginx restart

	            fi
    fi

}

# This function for Installing MySQL :
do_mysql()
{
	InsertSection "-- Installing MySQL --"
   	yum install mysql mysql-server -y
  	chkconfig --levels 235 mysqld on
   	/etc/init.d/mysqld start
   	echo -e " -- MySQL is Installed\t\t\t\t [ ${Green}Done${NC} ]"
}

# This function for Installing Mod_RPAF
doRpaf()
{
InsertSection "Installing Apache Mod_RPAF"

#comm=`apachectl -t -D DUMP_MODULES |grep rpaf|cut -d" " -f2|wc -l`
if [ -e /usr/local/apache/modules/mod_rpaf-2.0.so ]
then
	echo "	- Apache Mod_Rpaf Installation	[ Already Installed ]"
	echo "		- Please Check Mod_Rpaf Configuration Manually"
else
	echo -e "	- Download mod_rpaf Sources\t\t\t\t [ ${Green}Done${NC} ]"
	wget -q $S_RPAF
	tar -zxf mod_rpaf-0.6.tar.gz > /dev/null 2>&1
	cd mod_rpaf-0.6
	make rpaf-2.0 && make install-2.0 > /dev/null 2>&1
	apxs -i -c -n mod_rpaf-2.0.so mod_rpaf-2.0.c > /dev/null 2>&1
	# fix mod_rpaf 'can't load module' 23Nov 2010
	if [ -e /usr/lib64/httpd/modules/mod_rpaf-2.0.so ]
	then
		cp /usr/lib64/httpd/modules/mod_rpaf-2.0.so /usr/local/apache/modules/
	fi
	echo -e " -- Apache Mod_Rpaf Installation\t\t\t\t [ ${Green}Done${NC} ]"
	echo "LoadModule rpaf_module modules/mod_rpaf-2.0.so" > /usr/local/apache/conf/includes/pre_main_global.conf
	echo "#Mod_rpaf settings" >> /usr/local/apache/conf/includes/pre_main_global.conf
	echo "RPAFenable On" >> /usr/local/apache/conf/includes/pre_main_global.conf
	echo -e " -- Apache Mod_Rpaf Configuration\t\t\t\t [ ${Green}Done${NC} ]"
	RPAF_IP_OK=`grep RPAFproxy_ips  /usr/local/apache/conf/includes/pre_main_global.conf|wc -l`
	if [ $RPAF_IP_OK = 0 ]
	then
		echo "RPAFproxy_ips 127.0.0.1 $MAINIP" >> /usr/local/apache/conf/includes/pre_main_global.conf
		echo "RPAFsethostname On" >> /usr/local/apache/conf/includes/pre_main_global.conf
	elif [ $RPAF_IP_OK > 1 ]
	then
		echo "Error : Check Mod_Rpaf Configuration in : /usr/local/apache/conf/includes/pre_main_global.conf "
	else
		echo "Rpaf Configured check configuration if the X-Referrer didn't work for you"
	fi
fi

}

# This function for Installing Vhosts Configuration files
doConfig()
{



rm -rf /usr/local/src/EasyNginx/
mkdir -p /usr/local/src/EasyNginx/

# Calcultaing the memory size
RAM_SIZE=`free -m | grep Mem | awk '{print $2}'`
# Calcultaing the number of CPUs
CPU=`cat /proc/cpuinfo |grep -c '^processor'`
DCPU=`echo $CPU*2 |bc`
# To get 2/3 of RAM
RAM_use=`echo $RAM_SIZE*2/3 |bc`
# To get The pm.max.childern as it equal = 2/3 of RAM divided of 50
PAM_MAX=`echo $RAM_use/50 |bc`

cd ${BASE}
wget -q $CONF_TEMPLATE_URL
tar -xzf ntemplate.tar.gz > /dev/null 2>&1

 if [ ! -e /usr/local/cpanel ]
 then
InsertSection "Generating NGINX Configuration files"
echo -e " - Generate Nginx.conf file\t\t\t\t\t [ ${Green}Done${NC} ]"
 
  	
	cp -R -f $BASE/nginx_template/maintenance /usr/local/nginx/html/
        chown -R apache.apache  /usr/local/nginx/html/maintenance

       	if [ "$fpm" == "1" ]
         then
          VHOST_TEMPLATE=`cat $BASE/nginx_template/NocPanel-phpfpm.tpl`
cat > $NGINX_PATH/vhosts/default.conf << EOF
$VHOST_TEMPLATE
EOF
          
        elif [ "$fpm" == "0" ]
			then
          VHOST_TEMPLATE=`cat $BASE/nginx_template/NocPanel-reverse.tpl`
cat > $NGINX_PATH/vhosts/default.conf << EOF
$VHOST_TEMPLATE
EOF
	IP=`hostname -i`
    	replace REP_IP $IP -- $NGINX_PATH/vhosts/default.conf > /dev/null 2>&1
        replace REP_Apache_Port $Apache_Port -- $NGINX_PATH/vhosts/default.conf > /dev/null 2>&1
        fi
  
 else

InsertSection "Generate NGINX Vhosts Configuration files"
echo -e " - Generate Nginx.conf file\t\t\t [ ${Green}Done${NC} ]"
   cd /var/cpanel/users
   fpmport=9000
   for USER in *
   do
	for DOMAIN in `cat $USER | grep ^DNS | cut -d= -f2`
	do

		IP=`cat $USER|grep ^IP|cut -d= -f2`;
			ROOT_HOME=`grep ^$USER: /etc/passwd|cut -d: -f6`;
			IS_SUBDOM=`echo $DOMAIN|cut -d"." -f3`;
			SUBDOM=`echo $DOMAIN|cut -d"." -f1`;
			if [ "$IS_SUBDOM" = "com" ] || [ "$IS_SUBDOM" = "net" ] || [ "$IS_SUBDOM" = "org" ]
			then
				TXT="root   $ROOT_HOME/public_html/$SUBDOM; #$DOMAIN"
			        HOME="$ROOT_HOME/public_html/$SUBDOM"
			else
				TXT="root   $ROOT_HOME/public_html; #$DOMAIN"
				HOME="$ROOT_HOME/public_html"
			fi

			echo "[+] Converting $DOMAIN for $USER with $SUBDOM" >> /tmp/nginx_vh_list.tmp


			DOM_CONF=$NGINX_PATH/vhosts/$DOMAIN.conf
		  	DOM_FPM_CONF=$FPM_PATH/conf.d/$DOMAIN.conf


			if [ ! -d $NGINX_PATH/vhosts/  ]
			then
				mkdir $NGINX_PATH/vhosts
			fi

      		  	cp -R -f $BASE/nginx_template/maintenance $HOME/
	  		chown -R $USER.$USER $HOME/maintenance  > /dev/null 2>&1

			if [ "$fpm" == "1" ]
			then

		 		if [ ! -d $FPM_PATH/conf.d/  ]
			 	then
					mkdir $FPM_PATH/conf.d
				fi

			VHOST_TEMPLATE=`cat $BASE/nginx_template/nginx-phpfpm.conf.tpl`
			FPM_SITE_TEMPLATE=`cat $BASE/nginx_template/fpm-site.tpl`


cat > $DOM_CONF << EOF
$VHOST_TEMPLATE
EOF
				replace REP_DOMAIN $DOMAIN -- $DOM_CONF > /dev/null 2>&1
				replace REP_TXT "$TXT" -- $DOM_CONF > /dev/null 2>&1
				replace REP_HOME "$HOME" -- $DOM_CONF > /dev/null 2>&1
				replace REP_FPMPORT "$fpmport" -- $DOM_CONF > /dev/null 2>&1
                                replace REP_IP $IP -- $DOM_CONF > /dev/null 2>&1


cat > $DOM_FPM_CONF << EOF
$FPM_SITE_TEMPLATE
EOF
				replace REP_MAX $PAM_MAX -- $DOM_FPM_CONF > /dev/null 2>&1
				replace REP_CPU $CPU -- $DOM_FPM_CONF > /dev/null 2>&1
				replace REP_DCPU $DCPU -- $DOM_FPM_CONF > /dev/null 2>&1
				replace REP_DOMAIN $DOMAIN -- $DOM_FPM_CONF > /dev/null 2>&1
				replace REP_FPMPORT $fpmport -- $DOM_FPM_CONF > /dev/null 2>&1
			        replace REP_USER $USER 	-- $DOM_FPM_CONF > /dev/null >&1	                
				fpmport=`echo $[1 + $fpmport]`	

			elif [ "$fpm" == "0" ]
			then
			VHOST_TEMPLATE=`cat $BASE/nginx_template/nginx-reverse.conf.tpl`
cat > $DOM_CONF << EOF
$VHOST_TEMPLATE
EOF
				replace REP_DOMAIN $DOMAIN -- $DOM_CONF > /dev/null 2>&1
				replace REP_Apache_Port $Apache_Port -- $DOM_CONF > /dev/null 2>&1
				#replace REMOTE_IP $REMOTEIP -- $DOM_CONF > /dev/null 2>&1
		                replace REP_IP $IP -- $DOM_CONF > /dev/null 2>&1
				replace REP_TXT "$TXT" -- $DOM_CONF > /dev/null 2>&1

			fi
		
	done
done


#Fix Domain ROOT_HOME Path
cd /var/cpanel/users
for USER in *
do
	for DOMAIN in `cat $USER | grep ^DNS= | cut -d= -f2`
	do
		SUBDOM=`echo $DOMAIN|cut -d"." -f1`;
		TXT="/$SUBDOM;"
		DOM_CONF=/usr/local/nginx/vhosts/$DOMAIN.conf
		replace $TXT REPLACE_VAR -- $DOM_CONF > /dev/null 2>&1
		replace "REPLACE_VAR" ";" -- $DOM_CONF > /dev/null 2>&1 
       
	done
done


echo -e " - Nginx Virtual Hosts Configuration\t\t\t [ ${Green}Done${NC} ]"
vhostc=`ls /usr/local/nginx/vhosts/*.conf | wc -l`
echo -e " - Current Virtual hosts Configuration\t\t\t [ ${vhostc} Account include SubDomains ]"
echo -e " - Check /tmp/nginx_vh_list.tmp to View Full virtual host log"
 fi 
}

#####################
##		   ##
# The Main Function #
##		   ##
#####################

if [ $# != "0" ]
  then (

        if [ ! -e /usr/local/cpanel ] && [ ! -e /etc/init.d/mysqld ]
        then
		do_mysql
        fi 
  
	   if [ $1 == "-fpm" ]
	   then
		fpm="1"
		  if [ $2 == "-c" ]
		  then 
			doConfig
		        do_phpfpmHandelNginx
	          else
			do_Nginx
			do_phpfpm 
			doConfig
			do_phpfpmHandelNginx
 		 fi
    	  elif [ $1 == "-r" ]
	  then
	         fpm="0"
		 if [ $2 == "-c" ]
	         then 
			doRpaf
			doConfig
		        do_phpfpmHandelNginx
		 else
			do_Nginx
			doRpaf
			doConfig
			do_phpfpmHandelNginx
 		 fi
      	  else 
 		echo "        ####################### "
 		echo "        ##		     ## "
 		echo "        # ${Red}[EasyNginx.sh v3.0]${NC} # "
 		echo "        ##		     ## "
 		echo "        ####################### "
                echo "${Blue}This Script was developed by ArabHosters${NC}"
                echo "${Blue}It Build LEMP (EngineX - Mysql - PHP) AND/OR Configuring VHosts${NC}"
                echo "Usage : $0 -[fpm|r] [-fpm -c | -r -c] "
 		echo " ${Yellow}Option            Meaning:${NC}"
		echo " ${Yellow}------            --------${NC}"
                echo " ${LightGreen}-fpm${NC}		   ${LightBlue}Installing Nginx + PHP-FPM and make Nginx stands alone${NC}"
		echo " ${LightGreen}-r${NC}		   ${LightBlue}Installing Nginx as a reverse proxy${NC}"
		echo " ${LightGreen}-fpm -c${NC}           ${LightBlue}Making VHosts when Nginx is standing alone (without Installing Nginx)${NC}"
		echo " ${LightGreen}-r -c${NC}		   ${LightBlue}Making VHosts when Nginx is reverse proxy  (without Installing Nginx)${NC}"
                echo ""
         fi 
     
       )
else 
	echo "        ####################### "
 	echo "        ##		     ## "
 	echo "        # ${Red}[EasyNginx.sh v3.0]${NC} # "
	echo "        ##		     ## "
 	echo "        ####################### "
        echo "${Blue}This Script was developed by ArabHosters${NC}"
        echo "${Blue}It Build LEMP (EngineX - Mysql - PHP) AND/OR Configuring VHosts${NC}"
        echo "Usage : $0 -[fpm|r] [-fpm -c | -r -c] "
 	echo " ${Yellow}Option            Meaning:${NC}"
	echo " ${Yellow}------            --------${NC}"
        echo " ${LightGreen}-fpm${NC}		   ${LightBlue}Installing Nginx + PHP-FPM and make Nginx stands alone${NC}"
	echo " ${LightGreen}-r${NC}		   ${LightBlue}Installing Nginx as a reverse proxy${NC}"
	echo " ${LightGreen}-fpm -c${NC}           ${LightBlue}Making VHosts when Nginx is standing alone (without Installing Nginx)${NC}"
	echo " ${LightGreen}-r -c${NC}		   ${LightBlue}Making VHosts when Nginx is reverse proxy  (without Installing Nginx)${NC}"
        echo ""

fi





